server:
  port: 8080
  servlet:
    context-path: /api

openai:
  api:
    key: your-openai-api-key
    url: https://api.openai.com/v1/chat/completions

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html